-- Production-safe system defaults. This migration inserts no creators, aliases, handles,
-- submissions, candidates, or releases. Wikidata remains disabled and dry-run only.
INSERT OR IGNORE INTO source_configurations (
  source_name,
  enabled,
  scheduled_enabled,
  connector_version,
  access_mode,
  base_url,
  batch_size,
  maximum_pages_per_run,
  maximum_records_per_run,
  timeout_ms,
  retry_count,
  minimum_request_interval_ms,
  scope_configuration,
  candidate_creation_enabled,
  dry_run,
  source_license,
  attribution,
  configuration_status,
  created_at,
  updated_at
) VALUES (
  'wikidata',
  0,
  0,
  '0.1.0-poc',
  'official_api',
  'https://query.wikidata.org/sparql',
  5,
  1,
  10,
  5000,
  2,
  1000,
  '{"occupation_ids":["Q177220","Q639669"],"country_ids":[],"maximum_failed_records":3}',
  1,
  1,
  'CC0-1.0',
  'Wikidata contributors',
  'valid',
  '2026-07-22T00:00:00.000Z',
  '2026-07-22T00:00:00.000Z'
);
