/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=../../.env.types --include-runtime=false --env-interface=AdminBindings src/worker-configuration.d.ts` (hash: c913b5f2e386d25dd79b6582e684cd92)
interface __BaseEnv_AdminBindings {
  DB: D1Database;
  ADMIN_AUTH_FAILURE_RATE_LIMITER?: RateLimit;
  ADMIN_MUTATION_RATE_LIMITER?: RateLimit;
  ADMIN_INGESTION_RATE_LIMITER?: RateLimit;
  ASSETS: Fetcher;
  ENVIRONMENT: 'staging' | 'production';
  WORKER_NAME:
    | 'open-creator-registry-admin-staging'
    | 'open-creator-registry-admin'
    | 'open-creator-registry-admin-local';
  AUTH_PROVIDER: 'cloudflare_access' | 'unconfigured';
  ADMIN_ALLOWED_ORIGINS:
    | 'https://open-creator-registry-admin-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | 'https://open-creator-registry-admin.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | '';
  APPLICATION_URL:
    | 'https://open-creator-registry-admin-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | 'https://open-creator-registry-admin.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | 'http://localhost:5174';
  API_DOCUMENTATION_SERVER:
    | 'https://open-creator-registry-admin-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | 'https://open-creator-registry-admin.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | 'http://localhost:5174';
  CLOUDFLARE_ACCESS_TEAM_DOMAIN?: 'https://REPLACE_WITH_TEAM_NAME.cloudflareaccess.com';
  CLOUDFLARE_ACCESS_AUD?: 'REPLACE_WITH_STAGING_ACCESS_AUD' | 'REPLACE_WITH_PRODUCTION_ACCESS_AUD';
  WIKIDATA_FIXTURE_MODE: 'disabled';
  WIKIDATA_USER_AGENT?: 'OpenCreatorRegistry/0.1 (REPLACE_WITH_PROJECT_CONTACT_URL)';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface StagingEnv {
    DB: D1Database;
    ADMIN_AUTH_FAILURE_RATE_LIMITER: RateLimit;
    ADMIN_MUTATION_RATE_LIMITER: RateLimit;
    ADMIN_INGESTION_RATE_LIMITER: RateLimit;
    ASSETS: Fetcher;
    ENVIRONMENT: 'staging';
    WORKER_NAME: 'open-creator-registry-admin-staging';
    AUTH_PROVIDER: 'cloudflare_access';
    ADMIN_ALLOWED_ORIGINS: 'https://open-creator-registry-admin-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
    APPLICATION_URL: 'https://open-creator-registry-admin-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
    API_DOCUMENTATION_SERVER: 'https://open-creator-registry-admin-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
    CLOUDFLARE_ACCESS_TEAM_DOMAIN: 'https://REPLACE_WITH_TEAM_NAME.cloudflareaccess.com';
    CLOUDFLARE_ACCESS_AUD: 'REPLACE_WITH_STAGING_ACCESS_AUD';
    WIKIDATA_FIXTURE_MODE: 'disabled';
    WIKIDATA_USER_AGENT: 'OpenCreatorRegistry/0.1 (REPLACE_WITH_PROJECT_CONTACT_URL)';
  }
  interface ProductionEnv {
    DB: D1Database;
    ADMIN_AUTH_FAILURE_RATE_LIMITER: RateLimit;
    ADMIN_MUTATION_RATE_LIMITER: RateLimit;
    ADMIN_INGESTION_RATE_LIMITER: RateLimit;
    ASSETS: Fetcher;
    ENVIRONMENT: 'production';
    WORKER_NAME: 'open-creator-registry-admin';
    AUTH_PROVIDER: 'cloudflare_access';
    ADMIN_ALLOWED_ORIGINS: 'https://open-creator-registry-admin.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
    APPLICATION_URL: 'https://open-creator-registry-admin.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
    API_DOCUMENTATION_SERVER: 'https://open-creator-registry-admin.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
    CLOUDFLARE_ACCESS_TEAM_DOMAIN: 'https://REPLACE_WITH_TEAM_NAME.cloudflareaccess.com';
    CLOUDFLARE_ACCESS_AUD: 'REPLACE_WITH_PRODUCTION_ACCESS_AUD';
    WIKIDATA_FIXTURE_MODE: 'disabled';
    WIKIDATA_USER_AGENT: 'OpenCreatorRegistry/0.1 (REPLACE_WITH_PROJECT_CONTACT_URL)';
  }
  interface Env extends __BaseEnv_AdminBindings {}
}
interface AdminBindings extends __BaseEnv_AdminBindings {}
