/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=AdminBindings src/worker-configuration.d.ts` (hash: 9871996d2f2d067120b81fccaa92c904)
interface __BaseEnv_AdminBindings {
  DB: D1Database;
  ENVIRONMENT: 'production';
  AUTH_PROVIDER: 'unconfigured';
  ADMIN_ALLOWED_ORIGINS: '';
  WIKIDATA_FIXTURE_MODE?: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface Env extends __BaseEnv_AdminBindings {}
}
interface AdminBindings extends __BaseEnv_AdminBindings {}
