/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=../../.env.types --include-runtime=false --env-interface=PublicBindings src/worker-configuration.d.ts` (hash: 7482ac22d99cb95769499cf32b8f4e74)
interface __BaseEnv_PublicBindings {
  DB: D1Database;
  PUBLIC_HANDLE_CHECK_RATE_LIMITER?: RateLimit;
  PUBLIC_BATCH_CHECK_RATE_LIMITER?: RateLimit;
  PUBLIC_SUBMISSION_RATE_LIMITER?: RateLimit;
  ASSETS: Fetcher;
  ENVIRONMENT: 'staging' | 'production' | 'local';
  WORKER_NAME:
    | 'open-creator-registry-staging'
    | 'open-creator-registry'
    | 'open-creator-registry-public-local';
  ALLOWED_ORIGINS:
    | 'https://open-creator-registry-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | 'https://open-creator-registry.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | 'http://localhost:5173';
  APPLICATION_URL:
    | 'https://open-creator-registry-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | 'https://open-creator-registry.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | 'http://localhost:5173';
  API_DOCUMENTATION_SERVER:
    | 'https://open-creator-registry-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | 'https://open-creator-registry.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev'
    | 'http://localhost:5173';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface StagingEnv {
    DB: D1Database;
    PUBLIC_HANDLE_CHECK_RATE_LIMITER: RateLimit;
    PUBLIC_BATCH_CHECK_RATE_LIMITER: RateLimit;
    PUBLIC_SUBMISSION_RATE_LIMITER: RateLimit;
    ASSETS: Fetcher;
    ENVIRONMENT: 'staging';
    WORKER_NAME: 'open-creator-registry-staging';
    ALLOWED_ORIGINS: 'https://open-creator-registry-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
    APPLICATION_URL: 'https://open-creator-registry-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
    API_DOCUMENTATION_SERVER: 'https://open-creator-registry-staging.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
  }
  interface ProductionEnv {
    DB: D1Database;
    PUBLIC_HANDLE_CHECK_RATE_LIMITER: RateLimit;
    PUBLIC_BATCH_CHECK_RATE_LIMITER: RateLimit;
    PUBLIC_SUBMISSION_RATE_LIMITER: RateLimit;
    ASSETS: Fetcher;
    ENVIRONMENT: 'production';
    WORKER_NAME: 'open-creator-registry';
    ALLOWED_ORIGINS: 'https://open-creator-registry.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
    APPLICATION_URL: 'https://open-creator-registry.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
    API_DOCUMENTATION_SERVER: 'https://open-creator-registry.REPLACE_WITH_ACCOUNT_SUBDOMAIN.workers.dev';
  }
  interface Env extends __BaseEnv_PublicBindings {}
}
interface PublicBindings extends __BaseEnv_PublicBindings {}
