/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=PublicBindings src/worker-configuration.d.ts` (hash: 943b1660b59fc215cc4b7bb3ab3615c1)
interface __BaseEnv_PublicBindings {
  DB: D1Database;
  ENVIRONMENT: 'local';
  ALLOWED_ORIGINS: 'http://localhost:5173';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface Env extends __BaseEnv_PublicBindings {}
}
interface PublicBindings extends __BaseEnv_PublicBindings {}
