import { z } from 'zod';

import { registryClassifications } from '@open-creator-registry/contracts/classifications';
import {
  aliasTypes,
  creatorProtectionTiers,
  creatorReviewStatuses,
  reservationStatuses,
  sourceVerificationStatuses,
} from '@open-creator-registry/contracts/domain';
import {
  externalProfilePlatforms,
  externalProfileVerificationStatuses,
  externalProfileVisibilityStatuses,
  sourceAccessModes,
  sourceConfigurationStatuses,
} from '@open-creator-registry/contracts/sources';

const nullableString = z.string().trim().min(1).nullable().optional();
const countryCodes = z
  .array(z.string().regex(/^[A-Z]{2}$/u))
  .max(10)
  .nullable()
  .optional();

const seedCreatorSchema = z.object({
  id: z.uuid(),
  canonicalName: z.string().trim().min(2),
  entityType: z.string().trim().min(2),
  primaryCategory: nullableString,
  countryCodes,
  biographySummary: nullableString,
  notorietyScore: z.int().min(0).max(100),
  protectionTier: z.enum(creatorProtectionTiers),
  reviewStatus: z.enum(creatorReviewStatuses),
});

const seedSourceSchema = z.object({
  id: z.uuid(),
  creatorEntityId: z.uuid(),
  sourceName: z.string().trim().min(1),
  sourceEntityId: z.string().trim().min(1),
  sourceUrl: z.url().nullable().optional(),
  sourceLicense: nullableString,
  verificationStatus: z.enum(sourceVerificationStatuses),
  lastCheckedAt: z.iso.datetime().nullable().optional(),
});

const seedAliasSchema = z.object({
  id: z.uuid(),
  creatorEntityId: z.uuid(),
  alias: z.string().trim().min(2),
  language: nullableString,
  aliasType: z.enum(aliasTypes),
  confidenceScore: z.int().min(0).max(100),
  sourceId: z.uuid().nullable().optional(),
});

const seedReservedHandleSchema = z.object({
  id: z.uuid(),
  creatorEntityId: z.uuid(),
  displayHandle: z.string().trim().min(2),
  classification: z.enum(registryClassifications),
  confidenceScore: z.int().min(0).max(100),
  decisionSource: z.string().trim().min(2),
  reason: z.string().trim().min(10),
  status: z.enum(reservationStatuses),
});

const seedExternalProfileSchema = z.object({
  id: z.uuid(),
  creatorEntityId: z.uuid(),
  platform: z.enum(externalProfilePlatforms),
  platformAccountId: nullableString,
  platformHandle: nullableString,
  profileUrl: z.url().nullable().optional(),
  profileName: nullableString,
  isPrimary: z.boolean(),
  verificationStatus: z.enum(externalProfileVerificationStatuses),
  visibilityStatus: z.enum(externalProfileVisibilityStatuses),
  sourceName: z.string().trim().min(1),
  sourceReference: nullableString,
  sourceLicense: nullableString,
  confidenceScore: z.int().min(0).max(100),
  connectorVersion: nullableString,
  mappingVersion: nullableString,
  lastVerifiedAt: z.iso.datetime().nullable().optional(),
});

const seedSourceConfigurationSchema = z.object({
  sourceName: z.string().trim().min(1),
  enabled: z.boolean(),
  scheduledEnabled: z.boolean(),
  connectorVersion: z.string().trim().min(1),
  accessMode: z.enum(sourceAccessModes),
  baseUrl: z.url(),
  batchSize: z.int().min(1).max(100),
  maximumPagesPerRun: z.int().min(1).max(10),
  maximumRecordsPerRun: z.int().min(1).max(500),
  timeoutMs: z.int().min(100).max(30_000),
  retryCount: z.int().min(0).max(5),
  minimumRequestIntervalMs: z.int().min(0).max(60_000),
  scopeConfiguration: z.record(z.string(), z.unknown()),
  candidateCreationEnabled: z.boolean(),
  dryRun: z.boolean(),
  sourceLicense: z.string().trim().min(1),
  attribution: z.string().trim().min(1),
  configurationStatus: z.enum(sourceConfigurationStatuses),
});

export const demonstrationSeedSchema = z.object({
  metadata: z.object({
    label: z.literal('LOCAL DEMONSTRATION DATA — NOT AN AUTHORITATIVE REGISTRY'),
    version: z.string().min(1),
    generatedAt: z.iso.datetime(),
  }),
  creators: z.array(seedCreatorSchema).min(1),
  sources: z.array(seedSourceSchema).min(1),
  aliases: z.array(seedAliasSchema),
  reservedHandles: z.array(seedReservedHandleSchema).min(1),
  externalProfiles: z.array(seedExternalProfileSchema),
  sourceConfigurations: z.array(seedSourceConfigurationSchema),
  unlistedExamples: z.array(z.string().trim().min(2)).min(1),
});

export type DemonstrationSeedData = z.infer<typeof demonstrationSeedSchema>;

const creatorIds = {
  musician: '10000000-0000-4000-8000-000000000001',
  youtuber: '10000000-0000-4000-8000-000000000002',
  streamer: '10000000-0000-4000-8000-000000000003',
  comedian: '10000000-0000-4000-8000-000000000004',
  artist: '10000000-0000-4000-8000-000000000005',
  group: '10000000-0000-4000-8000-000000000006',
  regional: '10000000-0000-4000-8000-000000000007',
  commonName: '10000000-0000-4000-8000-000000000008',
  multiAlias: '10000000-0000-4000-8000-000000000009',
  collective: '10000000-0000-4000-8000-000000000010',
} as const;

const sourceIds = Object.fromEntries(
  Object.keys(creatorIds).map((key, index) => [
    key,
    `20000000-0000-4000-8000-${String(index + 1).padStart(12, '0')}`,
  ]),
) as Record<keyof typeof creatorIds, string>;

export const demonstrationSeedData: DemonstrationSeedData = {
  metadata: {
    label: 'LOCAL DEMONSTRATION DATA — NOT AN AUTHORITATIVE REGISTRY',
    version: 'phase-2-v1',
    generatedAt: '2026-01-15T00:00:00.000Z',
  },
  creators: [
    {
      id: creatorIds.musician,
      canonicalName: 'Demo Aurora Vale',
      entityType: 'person',
      primaryCategory: 'music',
      countryCodes: ['US'],
      biographySummary: 'Fictional critical-tier musician used only for local development.',
      notorietyScore: 98,
      protectionTier: 'critical',
      reviewStatus: 'approved',
    },
    {
      id: creatorIds.youtuber,
      canonicalName: 'Demo Frame Forge',
      entityType: 'person',
      primaryCategory: 'video',
      countryCodes: ['CA'],
      biographySummary: 'Fictional notable video creator used only for local development.',
      notorietyScore: 82,
      protectionTier: 'notable',
      reviewStatus: 'approved',
    },
    {
      id: creatorIds.streamer,
      canonicalName: 'Demo Nova Quest',
      entityType: 'person',
      primaryCategory: 'streaming',
      countryCodes: ['GB'],
      biographySummary: 'Fictional streamer used only for local development.',
      notorietyScore: 78,
      protectionTier: 'notable',
      reviewStatus: 'approved',
    },
    {
      id: creatorIds.comedian,
      canonicalName: 'Demo Kofi Laughs',
      entityType: 'person',
      primaryCategory: 'comedy',
      countryCodes: ['GH'],
      biographySummary: 'Fictional Ghanaian comedian used only for local development.',
      notorietyScore: 74,
      protectionTier: 'notable',
      reviewStatus: 'approved',
    },
    {
      id: creatorIds.artist,
      canonicalName: 'Demo Mira Sol',
      entityType: 'person',
      primaryCategory: 'visual_art',
      countryCodes: ['ES'],
      biographySummary: 'Fictional visual artist used only for local development.',
      notorietyScore: 68,
      protectionTier: 'watchlist',
      reviewStatus: 'approved',
    },
    {
      id: creatorIds.group,
      canonicalName: 'Demo Northstar Studio',
      entityType: 'group',
      primaryCategory: 'creator_group',
      countryCodes: ['SE'],
      biographySummary: 'Fictional creator group used only for local development.',
      notorietyScore: 80,
      protectionTier: 'notable',
      reviewStatus: 'approved',
    },
    {
      id: creatorIds.regional,
      canonicalName: 'Demo Amina Bello',
      entityType: 'person',
      primaryCategory: 'lifestyle',
      countryCodes: ['NG'],
      biographySummary: 'Fictional regional lifestyle creator used only for local development.',
      notorietyScore: 63,
      protectionTier: 'watchlist',
      reviewStatus: 'approved',
    },
    {
      id: creatorIds.commonName,
      canonicalName: 'Demo Alex Lee',
      entityType: 'person',
      primaryCategory: 'education',
      countryCodes: ['AU'],
      biographySummary: 'Fictional common-name record requiring conservative matching safeguards.',
      notorietyScore: 51,
      protectionTier: 'standard',
      reviewStatus: 'approved',
    },
    {
      id: creatorIds.multiAlias,
      canonicalName: 'Demo Luna Grey',
      entityType: 'person',
      primaryCategory: 'music',
      countryCodes: ['IE'],
      biographySummary: 'Fictional musician with multiple aliases used only for local development.',
      notorietyScore: 72,
      protectionTier: 'notable',
      reviewStatus: 'approved',
    },
    {
      id: creatorIds.collective,
      canonicalName: 'Demo River and Reed',
      entityType: 'collective',
      primaryCategory: 'design',
      countryCodes: ['ZA'],
      biographySummary: 'Fictional design collective used only for local development.',
      notorietyScore: 57,
      protectionTier: 'watchlist',
      reviewStatus: 'approved',
    },
  ],
  sources: Object.entries(creatorIds).map(([key, creatorEntityId], index) => ({
    id: sourceIds[key as keyof typeof creatorIds],
    creatorEntityId,
    sourceName: 'demonstration_catalog',
    sourceEntityId: `demo-creator-${String(index + 1).padStart(2, '0')}`,
    sourceUrl: null,
    sourceLicense: 'CC0-1.0 demonstration fixture',
    verificationStatus: 'verified',
    lastCheckedAt: '2026-01-15T00:00:00.000Z',
  })),
  aliases: [
    {
      id: '30000000-0000-4000-8000-000000000001',
      creatorEntityId: creatorIds.musician,
      alias: 'Aurora Vale Demo',
      language: 'en',
      aliasType: 'stage_name',
      confidenceScore: 100,
      sourceId: sourceIds.musician,
    },
    {
      id: '30000000-0000-4000-8000-000000000002',
      creatorEntityId: creatorIds.musician,
      alias: 'demo.aurora.vale',
      language: null,
      aliasType: 'official_handle',
      confidenceScore: 100,
      sourceId: sourceIds.musician,
    },
    {
      id: '30000000-0000-4000-8000-000000000003',
      creatorEntityId: creatorIds.youtuber,
      alias: 'FrameForge Demo',
      language: 'en',
      aliasType: 'known_alias',
      confidenceScore: 95,
      sourceId: sourceIds.youtuber,
    },
    {
      id: '30000000-0000-4000-8000-000000000004',
      creatorEntityId: creatorIds.streamer,
      alias: 'NovaQuest Demo',
      language: 'en',
      aliasType: 'official_handle',
      confidenceScore: 98,
      sourceId: sourceIds.streamer,
    },
    {
      id: '30000000-0000-4000-8000-000000000005',
      creatorEntityId: creatorIds.comedian,
      alias: 'Kofi Laughs Demo',
      language: 'en',
      aliasType: 'stage_name',
      confidenceScore: 96,
      sourceId: sourceIds.comedian,
    },
    {
      id: '30000000-0000-4000-8000-000000000006',
      creatorEntityId: creatorIds.artist,
      alias: 'MiraSol Demo',
      language: 'es',
      aliasType: 'known_alias',
      confidenceScore: 93,
      sourceId: sourceIds.artist,
    },
    {
      id: '30000000-0000-4000-8000-000000000007',
      creatorEntityId: creatorIds.regional,
      alias: 'AminaBello Demo',
      language: 'en',
      aliasType: 'official_handle',
      confidenceScore: 96,
      sourceId: sourceIds.regional,
    },
    {
      id: '30000000-0000-4000-8000-000000000008',
      creatorEntityId: creatorIds.commonName,
      alias: 'Alex Lee Demo Education',
      language: 'en',
      aliasType: 'protected_variant',
      confidenceScore: 82,
      sourceId: sourceIds.commonName,
    },
    {
      id: '30000000-0000-4000-8000-000000000009',
      creatorEntityId: creatorIds.multiAlias,
      alias: 'Luna Gray Demo',
      language: 'en',
      aliasType: 'known_alias',
      confidenceScore: 90,
      sourceId: sourceIds.multiAlias,
    },
    {
      id: '30000000-0000-4000-8000-000000000010',
      creatorEntityId: creatorIds.multiAlias,
      alias: 'L Grey Demo',
      language: 'en',
      aliasType: 'stage_name',
      confidenceScore: 88,
      sourceId: sourceIds.multiAlias,
    },
    {
      id: '30000000-0000-4000-8000-000000000011',
      creatorEntityId: creatorIds.multiAlias,
      alias: 'demo.luna.grey',
      language: null,
      aliasType: 'official_handle',
      confidenceScore: 99,
      sourceId: sourceIds.multiAlias,
    },
  ],
  reservedHandles: [
    {
      id: '40000000-0000-4000-8000-000000000001',
      creatorEntityId: creatorIds.musician,
      displayHandle: '@demo_aurora_vale',
      classification: 'hard_reserved',
      confidenceScore: 100,
      decisionSource: 'demonstration_seed',
      reason: 'Exact fictional creator handle reserved to exercise hard-reservation checks.',
      status: 'active',
    },
    {
      id: '40000000-0000-4000-8000-000000000002',
      creatorEntityId: creatorIds.musician,
      displayHandle: 'real-demo-aurora-vale',
      classification: 'soft_protected',
      confidenceScore: 92,
      decisionSource: 'demonstration_seed',
      reason: 'Official-style fictional variant used to exercise protected-variant review.',
      status: 'active',
    },
    {
      id: '40000000-0000-4000-8000-000000000003',
      creatorEntityId: creatorIds.musician,
      displayHandle: 'demo_aurora_vale_fans',
      classification: 'monitored',
      confidenceScore: 75,
      decisionSource: 'demonstration_seed',
      reason: 'Fictional fan-account variant used to exercise monitoring without identity proof.',
      status: 'active',
    },
    ...(
      [
        ['youtuber', 'demo_frame_forge'],
        ['streamer', 'demo_nova_quest'],
        ['comedian', 'demo_kofi_laughs'],
        ['artist', 'demo_mira_sol'],
        ['group', 'demo_northstar_studio'],
        ['regional', 'demo_amina_bello'],
        ['multiAlias', 'demo_luna_grey'],
        ['collective', 'demo_river_and_reed'],
      ] satisfies ReadonlyArray<readonly [keyof typeof creatorIds, string]>
    ).map(([key, displayHandle], index) => ({
      id: `40000000-0000-4000-8000-${String(index + 4).padStart(12, '0')}`,
      creatorEntityId: creatorIds[key],
      displayHandle,
      classification: 'hard_reserved' as const,
      confidenceScore: 96,
      decisionSource: 'demonstration_seed',
      reason: 'Exact fictional creator handle reserved for local repository and lookup testing.',
      status: 'active' as const,
    })),
    {
      id: '40000000-0000-4000-8000-000000000012',
      creatorEntityId: creatorIds.commonName,
      displayHandle: 'demo_alex_lee_archive',
      classification: 'monitored',
      confidenceScore: 60,
      decisionSource: 'demonstration_seed',
      reason: 'Common-name archive example requiring monitoring without broad name ownership.',
      status: 'active',
    },
  ],
  externalProfiles: [
    {
      id: '50000000-0000-4000-8000-000000000001',
      creatorEntityId: creatorIds.musician,
      platform: 'youtube',
      platformAccountId: 'UCDEMOAURORAVALE',
      platformHandle: '@DemoAuroraVale',
      profileUrl: 'https://www.youtube.com/@DemoAuroraVale',
      profileName: 'Demo Aurora Vale',
      isPrimary: true,
      verificationStatus: 'source_linked',
      visibilityStatus: 'public',
      sourceName: 'demonstration_catalog',
      sourceReference: 'demo-creator-01',
      sourceLicense: 'CC0-1.0 demonstration fixture',
      confidenceScore: 90,
      connectorVersion: null,
      mappingVersion: null,
      lastVerifiedAt: '2026-01-15T00:00:00.000Z',
    },
    {
      id: '50000000-0000-4000-8000-000000000002',
      creatorEntityId: creatorIds.musician,
      platform: 'official_website',
      platformAccountId: null,
      platformHandle: null,
      profileUrl: 'https://demo-aurora.example/',
      profileName: 'Demo Aurora official website',
      isPrimary: true,
      verificationStatus: 'manually_verified',
      visibilityStatus: 'public',
      sourceName: 'demonstration_catalog',
      sourceReference: 'demo-creator-01',
      sourceLicense: 'CC0-1.0 demonstration fixture',
      confidenceScore: 100,
      connectorVersion: null,
      mappingVersion: null,
      lastVerifiedAt: '2026-01-15T00:00:00.000Z',
    },
  ],
  sourceConfigurations: [
    {
      sourceName: 'wikidata',
      enabled: false,
      scheduledEnabled: false,
      connectorVersion: '0.1.0-poc',
      accessMode: 'official_api',
      baseUrl: 'https://query.wikidata.org/sparql',
      batchSize: 10,
      maximumPagesPerRun: 2,
      maximumRecordsPerRun: 20,
      timeoutMs: 5000,
      retryCount: 2,
      minimumRequestIntervalMs: 1000,
      scopeConfiguration: {
        occupation_ids: ['Q177220', 'Q639669'],
        country_ids: [],
        maximum_failed_records: 3,
      },
      candidateCreationEnabled: true,
      dryRun: true,
      sourceLicense: 'CC0-1.0',
      attribution: 'Wikidata contributors',
      configurationStatus: 'valid',
    },
  ],
  unlistedExamples: ['ordinary_unlisted_demo'],
};
